### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by azu** [textlint/textlint-plugin-html#21]
This project looking for new maintainers.
If you want to help us, then please say so.

This project has tasks that should be done.

- [x] Rename "html" to "DocumentHtml" mapping #19 
- [x] use rehype Status #2 

Personally, I do not have a project using html plugin.
So This project looking for real users and maintainers.
Of course, I can review new PRs.

**Comment by azu** [comment]
#23 Rewrite this.

- [ ] Update AST Explorer #25 
- [ ] We need to get more test.
  - https://github.com/textlint/textlint-plugin-html/issues/24
- [ ] Add Table Support
https://github.com/textlint/textlint-plugin-html/blob/08d7a6aacabd6313f85383e80c32c71bb4b99eb0/src/html-to-ast.ts#L138-L177
